x-app: &app-container-config
  build: .
  depends_on:
    - postgres
    - redis
    - celeryworker
  env_file:
    - .env
  environment:
    FLASK_ENV: ${FLASK_ENV:-development}
    BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME:-development}
    POSTGRES_HOST: postgres
  restart: unless-stopped
  stop_grace_period: "5s"
  tty: true
  volumes:
    - .:/var/www/app

version: "3.3"
services:

  web:
    <<: *app-container-config
    ports:
      - 80:80
    links:
      - postgres
      - redis
      - celeryworker

  redis:
    image: redis:alpine

  postgres:
    image: postgres:10
    env_file:
      - .env
    tty: true
    networks:
      - db
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - db
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin

  celeryworker:
    <<: *app-container-config
    entrypoint: ["flask", "celery", "worker", "--uid", "nobody", "--gid", "nogroup"]
    ports:
      - 5555:5555
    depends_on:
      - redis


networks:
  db:
    driver: bridge


volumes:
  postgres: {}
  pgadmin: {}
