site_name: CRWA Flagging Website Documentation
site_url: https://codeforboston.github.io/flagging/
site_description: Guide on developing and deploying the CRWA's flagging website.
site_author: Code For Boston
repo_url: https://github.com/codeforboston/flagging
repo_name: codeforboston/flagging
docs_dir: docs/src
nav:
- Home: index.md
- About: about.md
- Setup: setup.md
- Admin: admin.md
- Cloud:
    - Overview: cloud/index.md
    # - Manual Deployment: cloud/manual_heroku_deployment.md
    - Twitter Bot: cloud/twitter_bot.md
- Development:
    - Overview: development/index.md
    - Data: development/data.md
    - Predictive Models: development/predictive_models.md
    - Front-End: development/frontend.md
- Development Resources:
    - Overview: development_resources/index.md
    - Learning Resources: development_resources/learning_resources.md
    - Shell: development_resources/shell.md
theme:
  name: material
  palette:
    scheme: default
    primary: black
    accent: cyan
  icon:
    logo: fontawesome/regular/flag
  font:
    text: Opens Sans
    code: Roboto Mono
plugins:
  - macros
markdown_extensions:
- admonition
- pymdownx.tabbed: # https://facelessuser.github.io/pymdown-extensions/
    alternate_style: true
- pymdownx.keys
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: "!!python/name:pymdownx.superfences.fence_div_format"
- sane_lists
extra:
  flagging_website_url: https://crwa-flagging.herokuapp.com
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/codeforboston/flagging
  - icon: fontawesome/brands/meetup
    link: https://www.meetup.com/Code-for-Boston/
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/codeforboston
extra_javascript:
- https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
