name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v4
    - name: Python 3.10 Setup
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get update
    - name: Deploy docs
      uses: mhausenblas/mkdocs-deploy-gh-pages@1.17
      # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CONFIG_FILE: docs/mkdocs.yml
        REQUIREMENTS: docs/requirements.txt
