name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
    - name: Python 3.10 Setup
      uses: astral-sh/setup-uv@v5
      with:
        python-version: "3.12"
    - name: Install requirements for docs
      run: |
        sudo apt-get update
        uv pip install -r docs/requirements.txt
    - name: Build and deploy docs
      run: mkdocs gh-deploy --force
