name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        ports:
          - 5432:5432

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.7.3
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.3
    - name: Psycopg2 Linux dependencies
      run: sudo apt-get install python-dev libpq-dev
    - name: Install dependencies
      run: python -m pip install -r requirements/dev_osx.txt
    - name: Run unit-tests
      run: python -m pytest ./tests -vv
